[
  {
    "test": "connectivity",
    "success": false,
    "message": "Cannot connect to server: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /index.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xf99f55f22210>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "timestamp": "2025-09-03T17:51:39.145166",
    "details": {}
  }
]